---
- name: Add Ingress-Nginx Helm repository
  ansible.builtin.shell:
    cmd: helm --kubeconfig={{ kubeconfig }} repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  args:
    executable: /bin/bash

- name: Update Helm repositories
  ansible.builtin.shell:
    cmd: helm --kubeconfig={{ kubeconfig }} repo update
  args:
    executable: /bin/bash

- name: Install nginx-ingress with Helm
  ansible.builtin.shell:
    cmd: helm --kubeconfig={{ kubeconfig }} install nginx-ingress ingress-nginx/ingress-nginx 
        --namespace ingress-nginx 
        --create-namespace
        --set controller.hostPort.enabled={{ nginx_ingress_controller_hostPort_enabled }} 
        --set controller.hostNetwork={{ nginx_ingress_controller_hostNetwork }} 
        --set controller.service.type={{ nginx_ingress_controller_service_type }} 
        --set controller.kind={{ nginx_ingress_controller_kind }}
  args:
    executable: /bin/bash
  
