---
# defaults file for vault_secret_operator\
kubeconfig: /home/bexruz/.kube/config # set to your kube config
#! if you have created secret and collection change to false and show path
vso_create_directory: true
#! use unique word and never use it again all policy, auth, secret, tokens depend on this unique word!
vso_unique_name: days

vso_secret_name: "date"            # your secret engine name 
vso_secret_collection: "month/das" # path to your collection ("my_data", or like "data/my_info/number")
vso_vault_address: "https://vault0.bexruzdev.uz" #your vault cluster address
vso_vault_token: "hvs.RkovRS3dnj5iqUHP4ny2Iq7v"